### ISSUE TITLE
6.d Roast Commits In Need of Knowledgeable Review

### ISSUE THREAD

**Issue by zoffixznet** [perl6/6.d-prep#2]
Going to log here roast commits I spot during 6.d review that I've no idea if they're right or not:

* https://github.com/perl6/roast/commit/c435912c840b454d7ace6110a647cc24a9513580 -- the test includes `is repr('CUnion')`. Is that stuff proper spec or just Rakudo-specific thing? I see only two other tests that make use of `is repr` trait, so it doesn't seem to be something that's properly specced.
* [R#2073](https://github.com/rakudo/rakudo/issues/2073) -- `Bad propspec: Enum's :D accepts Enum's :U`

**Comment by jnthn** [comment]
> I see only two other tests that make use of is repr trait, so it doesn't seem to be something that's properly specced.

I think this is partly because the most useful place for `is repr(...)` is in NativeCall, but NativeCall currently is considered a Rakudo thing rather than a Perl 6 thing. Thus this feature is tested quite a bit, just not much in roast. There's surely heavy use of `is repr('CStruct')` in the module ecosystem, far more so than `is repr('CUnion')`.

That Perl 6 has representation polymorphism is certainly a part of the language design. The `is repr(...)` trait for specifying the representation to use has been around for a long while by now. The question is if we want to settle on it as being the design we want.

One argument against it is that it takes a string argument. I'd argue that's OK, because:

* It's checked at compile time anyway, so there's no safety argument against it
* There's no performance argument against a string identifier for the same reason
* Trying to have, say, an `enum` of available representations feels like a bootstrapping nightmare. Things have to bottom out *somewhere*. This is pretty bottom.

I didn't yet see an argument against the current `is repr(...)` design that held enough water to make me thing specing something other than what's already widely in use would be justified. So I'd say, let's consider it spec.

**Comment by zoffixznet** [comment]
OK. Thanks.

> Bad propspec: Enum's :D accepts Enum's :U

That was reverted out.
